name: house_worker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.7.2

dependencies:
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable:
  freezed_annotation: ^3.0.0
  google_fonts:
  intl: ^0.20.2
  logging: ^1.3.0
  package_info_plus: ^8.3.0
  riverpod: ^2.6.1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  mockito:
  pedantic_mono: ^1.30.0

flutter:
  uses-material-design: true
