name: house_worker
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+4

environment:
  sdk: 3.8.2

dependencies:
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.5.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.5
  firebase_remote_config: ^5.4.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  google_sign_in: ^6.3.0
  in_app_review: ^2.0.10
  logging: ^1.3.0
  package_info_plus: ^8.3.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  cider: ^0.2.8
  custom_lint: ^0.7.5
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  pedantic_mono: ^1.30.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
