inputs:
  google-service-json-base64-dev:
    required: true
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Generate Google service json file
      shell: bash
      run: echo "${{ inputs.google-service-json-base64-dev }}" | base64 -d > android/app/src/dev/google-services.json
      working-directory: ${{ inputs.working-directory }}
