runs:
  using: "composite"
  steps:
    - name: Cache Gradle
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
