inputs:
  firebase-options-dart-base64-emulator:
    required: true
  firebase-options-dart-base64-dev:
    required: true
  dart-defines-json-base64-dev:
    required: true
  working-directory:
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Firebase options files
      shell: bash
      run: |
        echo "${{ inputs.firebase-options-dart-base64-emulator }}" | base64 -d > lib/firebase_options_emulator.dart
        echo "${{ inputs.firebase-options-dart-base64-dev }}" | base64 -d > lib/firebase_options_dev.dart
    - name: Generate dart defines json file
      shell: bash
      run: |
        echo "${{ inputs.dart-defines-json-base64-dev }}" | base64 -d > dart-defines_dev.json
    - name: Generate automatic codes
      shell: bash
      run: bundle exec fastlane generate
      working-directory: ${{ inputs.working-directory }}
