inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Get Xcode version
      id: get-xcode-version
      run: |
        xcode_version="$(cat ios/.xcode-version)"
        echo "xcode-version=$xcode_version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Select Xcode Version
      run: sudo xcode-select -s "/Applications/Xcode_${{ steps.get-xcode-version.outputs.xcode-version }}.app/Contents/Developer"
      shell: bash
