inputs:
  working-directory:
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - name: Get Xcode version
      id: get-xcode-version
      shell: bash
      run: |
        xcode_version="$(cat .xcode-version)"
        echo "xcode-version=$xcode_version" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}
    - name: Select Xcode Version
      shell: bash
      run: sudo xcode-select -s "/Applications/Xcode_${{ steps.get-xcode-version.outputs.xcode-version }}.app/Contents/Developer"
